// This is an autogenerated file from Firebase Studio.

import { initializeApp, getApp, getApps } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getFirestore } from "firebase/firestore";
import { getStorage } from "firebase/storage";

const firebaseConfig = {
  "projectId": "skillverse-bafnh",
  "appId": "1:2867152427:web:6b9d80f3434e52d48bcc6e",
  "storageBucket": "skillverse-bafnh.appspot.com",
  "apiKey": "AIzaSyD_2sl6qytMDudgtVUDBlU1iYJ1OepEoXY",
  "authDomain": "skillverse-bafnh.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "2867152427"
};

// Initialize Firebase
const app = getApps().length ? getApp() : initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);
const storage = getStorage(app);

export { app, auth, db, storage };
